// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex
{
    public static class GetDataprocCluster
    {
        /// <summary>
        /// Get information about a Yandex Data Proc cluster. For more information, see [the official documentation](https://cloud.yandex.com/docs/data-proc/).
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Yandex = Pulumi.Yandex;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var foo = Output.Create(Yandex.GetDataprocCluster.InvokeAsync(new Yandex.GetDataprocClusterArgs
        ///         {
        ///             Name = "test",
        ///         }));
        ///         this.ServiceAccountId = foo.Apply(foo =&gt; foo.ServiceAccountId);
        ///     }
        /// 
        ///     [Output("serviceAccountId")]
        ///     public Output&lt;string&gt; ServiceAccountId { get; set; }
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDataprocClusterResult> InvokeAsync(GetDataprocClusterArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDataprocClusterResult>("yandex:index/getDataprocCluster:getDataprocCluster", args ?? new GetDataprocClusterArgs(), options.WithVersion());
    }


    public sealed class GetDataprocClusterArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the Data Proc cluster.
        /// </summary>
        [Input("clusterId")]
        public string? ClusterId { get; set; }

        /// <summary>
        /// The name of the Data Proc cluster.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetDataprocClusterArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDataprocClusterResult
    {
        /// <summary>
        /// Name of the Object Storage bucket used for Data Proc jobs.
        /// </summary>
        public readonly string Bucket;
        /// <summary>
        /// Configuration and resources of the cluster. The structure is documented below.
        /// </summary>
        public readonly Outputs.GetDataprocClusterClusterConfigResult ClusterConfig;
        public readonly string ClusterId;
        /// <summary>
        /// The Data Proc cluster creation timestamp.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Description of the Data Proc cluster.
        /// </summary>
        public readonly string Description;
        public readonly string FolderId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A set of key/value label pairs assigned to the Data Proc cluster.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// Name of the Data Proc subcluster.
        /// </summary>
        public readonly string Name;
        public readonly ImmutableArray<string> SecurityGroupIds;
        /// <summary>
        /// Service account used by the Data Proc agent to access resources of Yandex.Cloud.
        /// </summary>
        public readonly string ServiceAccountId;
        /// <summary>
        /// Whether UI proxy feature is enabled.
        /// </summary>
        public readonly bool UiProxy;
        /// <summary>
        /// ID of the availability zone where the cluster resides.
        /// </summary>
        public readonly string ZoneId;

        [OutputConstructor]
        private GetDataprocClusterResult(
            string bucket,

            Outputs.GetDataprocClusterClusterConfigResult clusterConfig,

            string clusterId,

            string createdAt,

            string description,

            string folderId,

            string id,

            ImmutableDictionary<string, string> labels,

            string name,

            ImmutableArray<string> securityGroupIds,

            string serviceAccountId,

            bool uiProxy,

            string zoneId)
        {
            Bucket = bucket;
            ClusterConfig = clusterConfig;
            ClusterId = clusterId;
            CreatedAt = createdAt;
            Description = description;
            FolderId = folderId;
            Id = id;
            Labels = labels;
            Name = name;
            SecurityGroupIds = securityGroupIds;
            ServiceAccountId = serviceAccountId;
            UiProxy = uiProxy;
            ZoneId = zoneId;
        }
    }
}
