// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi.Utilities;

namespace Pulumi.Yandex
{
    public static class GetFunctionScalingPolicy
    {
        public static Task<GetFunctionScalingPolicyResult> InvokeAsync(GetFunctionScalingPolicyArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetFunctionScalingPolicyResult>("yandex:index/getFunctionScalingPolicy:getFunctionScalingPolicy", args ?? new GetFunctionScalingPolicyArgs(), options.WithVersion());

        public static Output<GetFunctionScalingPolicyResult> Invoke(GetFunctionScalingPolicyInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetFunctionScalingPolicyResult>("yandex:index/getFunctionScalingPolicy:getFunctionScalingPolicy", args ?? new GetFunctionScalingPolicyInvokeArgs(), options.WithVersion());
    }


    public sealed class GetFunctionScalingPolicyArgs : Pulumi.InvokeArgs
    {
        [Input("functionId", required: true)]
        public string FunctionId { get; set; } = null!;

        [Input("policies")]
        private List<Inputs.GetFunctionScalingPolicyPolicyArgs>? _policies;
        public List<Inputs.GetFunctionScalingPolicyPolicyArgs> Policies
        {
            get => _policies ?? (_policies = new List<Inputs.GetFunctionScalingPolicyPolicyArgs>());
            set => _policies = value;
        }

        public GetFunctionScalingPolicyArgs()
        {
        }
    }

    public sealed class GetFunctionScalingPolicyInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("functionId", required: true)]
        public Input<string> FunctionId { get; set; } = null!;

        [Input("policies")]
        private InputList<Inputs.GetFunctionScalingPolicyPolicyInputArgs>? _policies;
        public InputList<Inputs.GetFunctionScalingPolicyPolicyInputArgs> Policies
        {
            get => _policies ?? (_policies = new InputList<Inputs.GetFunctionScalingPolicyPolicyInputArgs>());
            set => _policies = value;
        }

        public GetFunctionScalingPolicyInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetFunctionScalingPolicyResult
    {
        public readonly string FunctionId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetFunctionScalingPolicyPolicyResult> Policies;

        [OutputConstructor]
        private GetFunctionScalingPolicyResult(
            string functionId,

            string id,

            ImmutableArray<Outputs.GetFunctionScalingPolicyPolicyResult> policies)
        {
            FunctionId = functionId;
            Id = id;
            Policies = policies;
        }
    }
}
