// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Container Registry. For more information, see
// [the official documentation](https://cloud.yandex.com/docs/container-registry/concepts/registry)
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-yandex/sdk/go/yandex"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "some_registry_id"
// 		_, err := yandex.LookupContainerRegistry(ctx, &yandex.LookupContainerRegistryArgs{
// 			RegistryId: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupContainerRegistry(ctx *pulumi.Context, args *LookupContainerRegistryArgs, opts ...pulumi.InvokeOption) (*LookupContainerRegistryResult, error) {
	var rv LookupContainerRegistryResult
	err := ctx.Invoke("yandex:index/getContainerRegistry:getContainerRegistry", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getContainerRegistry.
type LookupContainerRegistryArgs struct {
	// Folder that the resource belongs to. If value is omitted, the default provider folder is used.
	FolderId *string `pulumi:"folderId"`
	// Labels to assign to this registry.
	Labels map[string]string `pulumi:"labels"`
	// Name of the registry.
	Name *string `pulumi:"name"`
	// The ID of a specific registry.
	RegistryId *string `pulumi:"registryId"`
}

// A collection of values returned by getContainerRegistry.
type LookupContainerRegistryResult struct {
	// Creation timestamp of this registry.
	CreatedAt string `pulumi:"createdAt"`
	FolderId  string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Labels to assign to this registry.
	Labels     map[string]string `pulumi:"labels"`
	Name       string            `pulumi:"name"`
	RegistryId string            `pulumi:"registryId"`
	// Status of the registry.
	Status string `pulumi:"status"`
}
