// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Compute disk. For more information, see
// [the official documentation](https://cloud.yandex.com/docs/compute/concepts/disk).
func LookupComputeDisk(ctx *pulumi.Context, args *LookupComputeDiskArgs, opts ...pulumi.InvokeOption) (*LookupComputeDiskResult, error) {
	var rv LookupComputeDiskResult
	err := ctx.Invoke("yandex:index/getComputeDisk:getComputeDisk", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getComputeDisk.
type LookupComputeDiskArgs struct {
	// The ID of a specific disk.
	DiskId              *string                            `pulumi:"diskId"`
	DiskPlacementPolicy *GetComputeDiskDiskPlacementPolicy `pulumi:"diskPlacementPolicy"`
	// ID of the folder that the disk belongs to.
	FolderId *string `pulumi:"folderId"`
	// Name of the disk.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getComputeDisk.
type LookupComputeDiskResult struct {
	// Disk creation timestamp.
	CreatedAt string `pulumi:"createdAt"`
	// Optional description of this disk.
	Description         string                             `pulumi:"description"`
	DiskId              string                             `pulumi:"diskId"`
	DiskPlacementPolicy *GetComputeDiskDiskPlacementPolicy `pulumi:"diskPlacementPolicy"`
	// ID of the folder that the disk belongs to.
	FolderId string `pulumi:"folderId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// ID of the source image that was used to create this disk.
	ImageId string `pulumi:"imageId"`
	// IDs of instances to which this disk is attached.
	InstanceIds []string `pulumi:"instanceIds"`
	// Map of labels applied to this disk.
	Labels map[string]string `pulumi:"labels"`
	Name   string            `pulumi:"name"`
	// License IDs that indicate which licenses are attached to this disk.
	ProductIds []string `pulumi:"productIds"`
	// Size of the disk, specified in Gb.
	Size int `pulumi:"size"`
	// Source snapshot that was used to create this disk.
	SnapshotId string `pulumi:"snapshotId"`
	// Status of the disk.
	Status string `pulumi:"status"`
	// Type of the disk.
	Type string `pulumi:"type"`
	// ID of the zone where the disk resides.
	Zone string `pulumi:"zone"`
}
