// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex IAM user account. For more information about accounts, see
// [Yandex.Cloud IAM accounts](https://cloud.yandex.com/docs/iam/concepts/#accounts).
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-yandex/sdk/go/yandex"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "my-yandex-login"
// 		_, err := yandex.GetIamUser(ctx, &yandex.GetIamUserArgs{
// 			Login: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// This data source is used to define [IAM User] that can be used by other resources.
func GetIamUser(ctx *pulumi.Context, args *GetIamUserArgs, opts ...pulumi.InvokeOption) (*GetIamUserResult, error) {
	var rv GetIamUserResult
	err := ctx.Invoke("yandex:index/getIamUser:getIamUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIamUser.
type GetIamUserArgs struct {
	// Login name used to sign in to Yandex Passport.
	Login *string `pulumi:"login"`
	// User ID used to manage IAM access bindings.
	UserId *string `pulumi:"userId"`
}

// A collection of values returned by getIamUser.
type GetIamUserResult struct {
	// Email address of user account.
	DefaultEmail string `pulumi:"defaultEmail"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Login name of IAM user account.
	Login string `pulumi:"login"`
	// ID of IAM user account.
	UserId string `pulumi:"userId"`
}
