// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Yandex Managed MySQL cluster. For more information, see
// [the official documentation](https://cloud.yandex.com/docs/managed-mysql/).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-yandex/sdk/go/yandex"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "test"
// 		foo, err := yandex.LookupMdbMysqlCluster(ctx, &yandex.LookupMdbMysqlClusterArgs{
// 			Name: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("networkId", foo.NetworkId)
// 		return nil
// 	})
// }
// ```
func LookupMdbMysqlCluster(ctx *pulumi.Context, args *LookupMdbMysqlClusterArgs, opts ...pulumi.InvokeOption) (*LookupMdbMysqlClusterResult, error) {
	var rv LookupMdbMysqlClusterResult
	err := ctx.Invoke("yandex:index/getMdbMysqlCluster:getMdbMysqlCluster", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMdbMysqlCluster.
type LookupMdbMysqlClusterArgs struct {
	// Access policy to the MySQL cluster. The structure is documented below.
	Access *GetMdbMysqlClusterAccess `pulumi:"access"`
	// The ID of the MySQL cluster.
	ClusterId *string `pulumi:"clusterId"`
	// Description of the MySQL cluster.
	Description *string `pulumi:"description"`
	// The ID of the folder that the resource belongs to. If it is not provided, the default provider folder is used.
	FolderId *string `pulumi:"folderId"`
	// A set of key/value label pairs to assign to the MySQL cluster.
	Labels map[string]string `pulumi:"labels"`
	// MySQL cluster config.
	MysqlConfig map[string]string `pulumi:"mysqlConfig"`
	// The name of the MySQL cluster.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getMdbMysqlCluster.
type LookupMdbMysqlClusterResult struct {
	// Access policy to the MySQL cluster. The structure is documented below.
	Access            GetMdbMysqlClusterAccess            `pulumi:"access"`
	BackupWindowStart GetMdbMysqlClusterBackupWindowStart `pulumi:"backupWindowStart"`
	ClusterId         string                              `pulumi:"clusterId"`
	// Creation timestamp of the key.
	CreatedAt string `pulumi:"createdAt"`
	// A database of the MySQL cluster. The structure is documented below.
	Databases []GetMdbMysqlClusterDatabase `pulumi:"databases"`
	// Description of the MySQL cluster.
	Description *string `pulumi:"description"`
	// Deployment environment of the MySQL cluster.
	Environment string `pulumi:"environment"`
	FolderId    string `pulumi:"folderId"`
	// Aggregated health of the cluster.
	Health string `pulumi:"health"`
	// A host of the MySQL cluster. The structure is documented below.
	Hosts []GetMdbMysqlClusterHost `pulumi:"hosts"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A set of key/value label pairs to assign to the MySQL cluster.
	Labels map[string]string `pulumi:"labels"`
	// Maintenance window settings of the MySQL cluster. The structure is documented below.
	MaintenanceWindow GetMdbMysqlClusterMaintenanceWindow `pulumi:"maintenanceWindow"`
	// MySQL cluster config.
	MysqlConfig map[string]string `pulumi:"mysqlConfig"`
	// The name of the database.
	Name string `pulumi:"name"`
	// ID of the network, to which the MySQL cluster belongs.
	NetworkId string `pulumi:"networkId"`
	// Resources allocated to hosts of the MySQL cluster. The structure is documented below.
	Resources GetMdbMysqlClusterResources `pulumi:"resources"`
	// A set of ids of security groups assigned to hosts of the cluster.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// Status of the cluster.
	Status string `pulumi:"status"`
	// A user of the MySQL cluster. The structure is documented below.
	Users []GetMdbMysqlClusterUser `pulumi:"users"`
	// Version of the MySQL cluster.
	Version string `pulumi:"version"`
}
