// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class ComputeDiskDiskPlacementPolicy
    {
        /// <summary>
        /// Specifies Disk Placement Group id.
        /// </summary>
        public readonly string DiskPlacementGroupId;

        [OutputConstructor]
        private ComputeDiskDiskPlacementPolicy(string diskPlacementGroupId)
        {
            DiskPlacementGroupId = diskPlacementGroupId;
        }
    }
}
