// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class DataprocClusterClusterConfigSubclusterSpecResources
    {
        /// <summary>
        /// Volume of the storage available to a host, in gigabytes.
        /// </summary>
        public readonly int DiskSize;
        /// <summary>
        /// Type of the storage of a host. One of `network-hdd` (default) or `network-ssd`.
        /// </summary>
        public readonly string? DiskTypeId;
        /// <summary>
        /// The ID of the preset for computational resources available to a host. All available presets are listed in the [documentation](https://cloud.yandex.com/docs/data-proc/concepts/instance-types).
        /// </summary>
        public readonly string ResourcePresetId;

        [OutputConstructor]
        private DataprocClusterClusterConfigSubclusterSpecResources(
            int diskSize,

            string? diskTypeId,

            string resourcePresetId)
        {
            DiskSize = diskSize;
            DiskTypeId = diskTypeId;
            ResourcePresetId = resourcePresetId;
        }
    }
}
