// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetAlbVirtualHostRouteGrpcRouteGrpcRouteActionResult
    {
        /// <summary>
        /// If set, will automatically rewrite host.
        /// </summary>
        public readonly bool AutoHostRewrite;
        /// <summary>
        /// Backend group to route requests.
        /// </summary>
        public readonly string BackendGroupId;
        /// <summary>
        /// Host rewrite specifier.
        /// </summary>
        public readonly string HostRewrite;
        /// <summary>
        /// Specifies the idle timeout (time without any data transfer for the active request) for the route. It
        /// is useful for streaming scenarios - one should set idle_timeout to something meaningful and max_timeout to the maximum
        /// time the stream is allowed to be alive. If not specified, there is no per-route idle timeout.
        /// </summary>
        public readonly string IdleTimeout;
        /// <summary>
        /// Lower timeout may be specified by the client (using grpc-timeout header). If not set, default is 60
        /// seconds.
        /// </summary>
        public readonly string MaxTimeout;

        [OutputConstructor]
        private GetAlbVirtualHostRouteGrpcRouteGrpcRouteActionResult(
            bool autoHostRewrite,

            string backendGroupId,

            string hostRewrite,

            string idleTimeout,

            string maxTimeout)
        {
            AutoHostRewrite = autoHostRewrite;
            BackendGroupId = backendGroupId;
            HostRewrite = hostRewrite;
            IdleTimeout = idleTimeout;
            MaxTimeout = maxTimeout;
        }
    }
}
