// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetComputeInstanceGroupLoadBalancerStateResult
    {
        /// <summary>
        /// The status message of the target group.
        /// </summary>
        public readonly string StatusMessage;
        /// <summary>
        /// The ID of the target group.
        /// </summary>
        public readonly string TargetGroupId;

        [OutputConstructor]
        private GetComputeInstanceGroupLoadBalancerStateResult(
            string statusMessage,

            string targetGroupId)
        {
            StatusMessage = statusMessage;
            TargetGroupId = targetGroupId;
        }
    }
}
