// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetKubernetesNodeGroupScalePolicyResult
    {
        /// <summary>
        /// Scale policy for an autoscaled node group. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetKubernetesNodeGroupScalePolicyAutoScaleResult> AutoScales;
        /// <summary>
        /// Scale policy for a fixed scale node group. The structure is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetKubernetesNodeGroupScalePolicyFixedScaleResult> FixedScales;

        [OutputConstructor]
        private GetKubernetesNodeGroupScalePolicyResult(
            ImmutableArray<Outputs.GetKubernetesNodeGroupScalePolicyAutoScaleResult> autoScales,

            ImmutableArray<Outputs.GetKubernetesNodeGroupScalePolicyFixedScaleResult> fixedScales)
        {
            AutoScales = autoScales;
            FixedScales = fixedScales;
        }
    }
}
