// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Outputs
{

    [OutputType]
    public sealed class GetMdbClickhouseClusterClickhouseConfigGraphiteRollupPatternResult
    {
        /// <summary>
        /// Aggregation function name.
        /// </summary>
        public readonly string Function;
        /// <summary>
        /// Regular expression that the metric name must match.
        /// </summary>
        public readonly string? Regexp;
        /// <summary>
        /// Retain parameters.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetMdbClickhouseClusterClickhouseConfigGraphiteRollupPatternRetentionResult> Retentions;

        [OutputConstructor]
        private GetMdbClickhouseClusterClickhouseConfigGraphiteRollupPatternResult(
            string function,

            string? regexp,

            ImmutableArray<Outputs.GetMdbClickhouseClusterClickhouseConfigGraphiteRollupPatternRetentionResult> retentions)
        {
            Function = function;
            Regexp = regexp;
            Retentions = retentions;
        }
    }
}
