// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class GetMdbClickhouseClusterCloudStorageArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// (Required) Whether to use Yandex Object Storage for storing ClickHouse data. Can be either `true` or `false`.
        /// </summary>
        [Input("enabled", required: true)]
        public bool Enabled { get; set; }

        public GetMdbClickhouseClusterCloudStorageArgs()
        {
        }
    }
}
