// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yandex.Inputs
{

    public sealed class MdbClickhouseClusterShardGroupArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the shard group.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Graphite rollup configuration name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("shardNames", required: true)]
        private InputList<string>? _shardNames;

        /// <summary>
        /// List of shards names that belong to the shard group.
        /// </summary>
        public InputList<string> ShardNames
        {
            get => _shardNames ?? (_shardNames = new InputList<string>());
            set => _shardNames = value;
        }

        public MdbClickhouseClusterShardGroupArgs()
        {
        }
    }
}
