env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  # NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  # PROVIDER: yandex
  # PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  # PULUMI_API: https://api.pulumi-staging.io
  # PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  # PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  # PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  # TRAVIS_OS_NAME: linux
  # YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
  # YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  # YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_FILE }}
jobs:
  update_bridge:
    name: Update bridge
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.goversion}}
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.2.0
      with:
        repo: pulumi/pulumictl
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v2
    - name: Setup DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnetversion}}
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.nodeversion}}
        registry-url: https://registry.npmjs.org
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.pythonversion}}
    - run: sudo npm install -g chg
    - name: Update pulumi-terraform-bridge
      run: cd provider && go mod edit -require github.com/pulumi/pulumi-terraform-bridge/v3@v${{ github.event.inputs.bridge_version }} && go mod tidy
    - name: Update Pulumi SDK (provider/go.mod)
      run: cd provider && go mod edit -require github.com/pulumi/pulumi/sdk/v3@v${{ github.event.inputs.sdk_version }} && go mod tidy
    - name: Update Pulumi SDK (sdk/go.mod)
      run: cd sdk && go mod edit -require github.com/pulumi/pulumi/sdk/v3@v${{ github.event.inputs.sdk_version }} && go mod tidy
    - run: make tfgen
    - run: make build_sdks
    - name: commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_email: bot@pulumi.com
        author_name: pulumi-bot
        branch: pulumi-bot/bridge-v${{ github.event.inputs.version }}-${{ github.run_id}}
        branch_mode: create
        message: Update pulumi-terraform-bridge to v${{ github.event.inputs.bridge_version }}
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        author_name: pulumi-bot
        destination_branch: master
        github_token: ${{ secrets.PULUMI_BOT_TOKEN }}
        pr_allow_empty: false
        pr_body: This pull request was generated automatically by the update-bridge workflow in this repository.
        pr_reviewer: jkodroff
        pr_title: Update pulumi-terraform-bridge to v${{ github.event.inputs.bridge_version }}
        source_branch: pulumi-bot/bridge-v${{ github.event.inputs.version }}-${{ github.run_id}}
    strategy:
      fail-fast: true
      matrix:
        dotnetversion:
        - 3.1.301
        goversion:
        - 1.16.x
        nodeversion:
        - 14.x
        pythonversion:
        - "3.7"
"on":
  workflow_dispatch:
    inputs:
      bridge_version:
        required: true
        description: "The version of pulumi/pulumi-terraform-bridge to update to. Do not include the 'v' prefix. Must be major version 3."
        type: string
      sdk_version:
        required: true
        description: "The version of pulumi/pulumi/sdk to update to. Do not include the 'v' prefix. Must be major version 3."
        type: string
