// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * A VM instance resource. For more information, see
 * [the official documentation](https://cloud.yandex.com/docs/compute/concepts/vm).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as fs from "fs";
 * import * as yandex from "@pulumi/yandex";
 *
 * const fooVpcNetwork = new yandex.VpcNetwork("foo", {});
 * const fooVpcSubnet = new yandex.VpcSubnet("foo", {
 *     networkId: fooVpcNetwork.id,
 *     zone: "ru-central1-a",
 * });
 * const defaultComputeInstance = new yandex.ComputeInstance("default", {
 *     bootDisk: {
 *         initializeParams: {
 *             imageId: "image_id",
 *         },
 *     },
 *     metadata: {
 *         foo: "bar",
 *         "ssh-keys": `ubuntu:${fs.readFileSync("~/.ssh/id_rsa.pub", "utf-8")}`,
 *     },
 *     networkInterfaces: [{
 *         subnetId: fooVpcSubnet.id,
 *     }],
 *     platformId: "standard-v1",
 *     resources: {
 *         cores: 2,
 *         memory: 4,
 *     },
 *     zone: "ru-central1-a",
 * });
 * ```
 *
 * ## Import
 *
 * Instances can be imported using the `ID` of an instance, e.g.
 *
 * ```sh
 *  $ pulumi import yandex:index/computeInstance:ComputeInstance default instance_id
 * ```
 */
export class ComputeInstance extends pulumi.CustomResource {
    /**
     * Get an existing ComputeInstance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ComputeInstanceState, opts?: pulumi.CustomResourceOptions): ComputeInstance {
        return new ComputeInstance(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yandex:index/computeInstance:ComputeInstance';

    /**
     * Returns true if the given object is an instance of ComputeInstance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ComputeInstance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ComputeInstance.__pulumiType;
    }

    public readonly allowStoppingForUpdate!: pulumi.Output<boolean | undefined>;
    /**
     * The boot disk for the instance. The structure is documented below.
     */
    public readonly bootDisk!: pulumi.Output<outputs.ComputeInstanceBootDisk>;
    /**
     * Creation timestamp of the instance.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Description of the boot disk.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The ID of the folder that the resource belongs to. If it
     * is not provided, the default provider folder is used.
     */
    public readonly folderId!: pulumi.Output<string>;
    /**
     * The fully qualified DNS name of this instance.
     */
    public /*out*/ readonly fqdn!: pulumi.Output<string>;
    /**
     * Host name for the instance. This field is used to generate the instance `fqdn` value. 
     * The host name must be unique within the network and region. If not specified, the host name will be equal
     * to `id` of the instance and `fqdn` will be `<id>.auto.internal`.
     * Otherwise FQDN will be `<hostname>.<region_id>.internal`.
     */
    public readonly hostname!: pulumi.Output<string>;
    /**
     * A set of key/value label pairs to assign to the instance.
     */
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Metadata key/value pairs to make available from
     * within the instance.
     */
    public readonly metadata!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Name of the boot disk.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Type of network acceleration. The default is `standard`. Values: `standard`, `softwareAccelerated`
     */
    public readonly networkAccelerationType!: pulumi.Output<string | undefined>;
    /**
     * Networks to attach to the instance. This can
     * be specified multiple times. The structure is documented below.
     */
    public readonly networkInterfaces!: pulumi.Output<outputs.ComputeInstanceNetworkInterface[]>;
    /**
     * The placement policy configuration. The structure is documented below.
     */
    public readonly placementPolicy!: pulumi.Output<outputs.ComputeInstancePlacementPolicy>;
    /**
     * The type of virtual machine to create. The default is 'standard-v1'.
     */
    public readonly platformId!: pulumi.Output<string | undefined>;
    /**
     * Compute resources that are allocated for the instance. The structure is documented below.
     */
    public readonly resources!: pulumi.Output<outputs.ComputeInstanceResources>;
    /**
     * Scheduling policy configuration. The structure is documented below.
     */
    public readonly schedulingPolicy!: pulumi.Output<outputs.ComputeInstanceSchedulingPolicy>;
    /**
     * A list of disks to attach to the instance. The structure is documented below.
     * **Note**: The `allowStoppingForUpdate` property must be set to true in order to update this structure.
     */
    public readonly secondaryDisks!: pulumi.Output<outputs.ComputeInstanceSecondaryDisk[] | undefined>;
    /**
     * ID of the service account authorized for this instance.
     */
    public readonly serviceAccountId!: pulumi.Output<string>;
    /**
     * The status of this instance.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * The availability zone where the virtual machine will be created. If it is not provided,
     * the default provider folder is used.
     */
    public readonly zone!: pulumi.Output<string>;

    /**
     * Create a ComputeInstance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ComputeInstanceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ComputeInstanceArgs | ComputeInstanceState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ComputeInstanceState | undefined;
            inputs["allowStoppingForUpdate"] = state ? state.allowStoppingForUpdate : undefined;
            inputs["bootDisk"] = state ? state.bootDisk : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["folderId"] = state ? state.folderId : undefined;
            inputs["fqdn"] = state ? state.fqdn : undefined;
            inputs["hostname"] = state ? state.hostname : undefined;
            inputs["labels"] = state ? state.labels : undefined;
            inputs["metadata"] = state ? state.metadata : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["networkAccelerationType"] = state ? state.networkAccelerationType : undefined;
            inputs["networkInterfaces"] = state ? state.networkInterfaces : undefined;
            inputs["placementPolicy"] = state ? state.placementPolicy : undefined;
            inputs["platformId"] = state ? state.platformId : undefined;
            inputs["resources"] = state ? state.resources : undefined;
            inputs["schedulingPolicy"] = state ? state.schedulingPolicy : undefined;
            inputs["secondaryDisks"] = state ? state.secondaryDisks : undefined;
            inputs["serviceAccountId"] = state ? state.serviceAccountId : undefined;
            inputs["status"] = state ? state.status : undefined;
            inputs["zone"] = state ? state.zone : undefined;
        } else {
            const args = argsOrState as ComputeInstanceArgs | undefined;
            if ((!args || args.bootDisk === undefined) && !opts.urn) {
                throw new Error("Missing required property 'bootDisk'");
            }
            if ((!args || args.networkInterfaces === undefined) && !opts.urn) {
                throw new Error("Missing required property 'networkInterfaces'");
            }
            if ((!args || args.resources === undefined) && !opts.urn) {
                throw new Error("Missing required property 'resources'");
            }
            inputs["allowStoppingForUpdate"] = args ? args.allowStoppingForUpdate : undefined;
            inputs["bootDisk"] = args ? args.bootDisk : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["folderId"] = args ? args.folderId : undefined;
            inputs["hostname"] = args ? args.hostname : undefined;
            inputs["labels"] = args ? args.labels : undefined;
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["networkAccelerationType"] = args ? args.networkAccelerationType : undefined;
            inputs["networkInterfaces"] = args ? args.networkInterfaces : undefined;
            inputs["placementPolicy"] = args ? args.placementPolicy : undefined;
            inputs["platformId"] = args ? args.platformId : undefined;
            inputs["resources"] = args ? args.resources : undefined;
            inputs["schedulingPolicy"] = args ? args.schedulingPolicy : undefined;
            inputs["secondaryDisks"] = args ? args.secondaryDisks : undefined;
            inputs["serviceAccountId"] = args ? args.serviceAccountId : undefined;
            inputs["zone"] = args ? args.zone : undefined;
            inputs["createdAt"] = undefined /*out*/;
            inputs["fqdn"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(ComputeInstance.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ComputeInstance resources.
 */
export interface ComputeInstanceState {
    readonly allowStoppingForUpdate?: pulumi.Input<boolean>;
    /**
     * The boot disk for the instance. The structure is documented below.
     */
    readonly bootDisk?: pulumi.Input<inputs.ComputeInstanceBootDisk>;
    /**
     * Creation timestamp of the instance.
     */
    readonly createdAt?: pulumi.Input<string>;
    /**
     * Description of the boot disk.
     */
    readonly description?: pulumi.Input<string>;
    /**
     * The ID of the folder that the resource belongs to. If it
     * is not provided, the default provider folder is used.
     */
    readonly folderId?: pulumi.Input<string>;
    /**
     * The fully qualified DNS name of this instance.
     */
    readonly fqdn?: pulumi.Input<string>;
    /**
     * Host name for the instance. This field is used to generate the instance `fqdn` value. 
     * The host name must be unique within the network and region. If not specified, the host name will be equal
     * to `id` of the instance and `fqdn` will be `<id>.auto.internal`.
     * Otherwise FQDN will be `<hostname>.<region_id>.internal`.
     */
    readonly hostname?: pulumi.Input<string>;
    /**
     * A set of key/value label pairs to assign to the instance.
     */
    readonly labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Metadata key/value pairs to make available from
     * within the instance.
     */
    readonly metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the boot disk.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Type of network acceleration. The default is `standard`. Values: `standard`, `softwareAccelerated`
     */
    readonly networkAccelerationType?: pulumi.Input<string>;
    /**
     * Networks to attach to the instance. This can
     * be specified multiple times. The structure is documented below.
     */
    readonly networkInterfaces?: pulumi.Input<pulumi.Input<inputs.ComputeInstanceNetworkInterface>[]>;
    /**
     * The placement policy configuration. The structure is documented below.
     */
    readonly placementPolicy?: pulumi.Input<inputs.ComputeInstancePlacementPolicy>;
    /**
     * The type of virtual machine to create. The default is 'standard-v1'.
     */
    readonly platformId?: pulumi.Input<string>;
    /**
     * Compute resources that are allocated for the instance. The structure is documented below.
     */
    readonly resources?: pulumi.Input<inputs.ComputeInstanceResources>;
    /**
     * Scheduling policy configuration. The structure is documented below.
     */
    readonly schedulingPolicy?: pulumi.Input<inputs.ComputeInstanceSchedulingPolicy>;
    /**
     * A list of disks to attach to the instance. The structure is documented below.
     * **Note**: The `allowStoppingForUpdate` property must be set to true in order to update this structure.
     */
    readonly secondaryDisks?: pulumi.Input<pulumi.Input<inputs.ComputeInstanceSecondaryDisk>[]>;
    /**
     * ID of the service account authorized for this instance.
     */
    readonly serviceAccountId?: pulumi.Input<string>;
    /**
     * The status of this instance.
     */
    readonly status?: pulumi.Input<string>;
    /**
     * The availability zone where the virtual machine will be created. If it is not provided,
     * the default provider folder is used.
     */
    readonly zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ComputeInstance resource.
 */
export interface ComputeInstanceArgs {
    readonly allowStoppingForUpdate?: pulumi.Input<boolean>;
    /**
     * The boot disk for the instance. The structure is documented below.
     */
    readonly bootDisk: pulumi.Input<inputs.ComputeInstanceBootDisk>;
    /**
     * Description of the boot disk.
     */
    readonly description?: pulumi.Input<string>;
    /**
     * The ID of the folder that the resource belongs to. If it
     * is not provided, the default provider folder is used.
     */
    readonly folderId?: pulumi.Input<string>;
    /**
     * Host name for the instance. This field is used to generate the instance `fqdn` value. 
     * The host name must be unique within the network and region. If not specified, the host name will be equal
     * to `id` of the instance and `fqdn` will be `<id>.auto.internal`.
     * Otherwise FQDN will be `<hostname>.<region_id>.internal`.
     */
    readonly hostname?: pulumi.Input<string>;
    /**
     * A set of key/value label pairs to assign to the instance.
     */
    readonly labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Metadata key/value pairs to make available from
     * within the instance.
     */
    readonly metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the boot disk.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Type of network acceleration. The default is `standard`. Values: `standard`, `softwareAccelerated`
     */
    readonly networkAccelerationType?: pulumi.Input<string>;
    /**
     * Networks to attach to the instance. This can
     * be specified multiple times. The structure is documented below.
     */
    readonly networkInterfaces: pulumi.Input<pulumi.Input<inputs.ComputeInstanceNetworkInterface>[]>;
    /**
     * The placement policy configuration. The structure is documented below.
     */
    readonly placementPolicy?: pulumi.Input<inputs.ComputeInstancePlacementPolicy>;
    /**
     * The type of virtual machine to create. The default is 'standard-v1'.
     */
    readonly platformId?: pulumi.Input<string>;
    /**
     * Compute resources that are allocated for the instance. The structure is documented below.
     */
    readonly resources: pulumi.Input<inputs.ComputeInstanceResources>;
    /**
     * Scheduling policy configuration. The structure is documented below.
     */
    readonly schedulingPolicy?: pulumi.Input<inputs.ComputeInstanceSchedulingPolicy>;
    /**
     * A list of disks to attach to the instance. The structure is documented below.
     * **Note**: The `allowStoppingForUpdate` property must be set to true in order to update this structure.
     */
    readonly secondaryDisks?: pulumi.Input<pulumi.Input<inputs.ComputeInstanceSecondaryDisk>[]>;
    /**
     * ID of the service account authorized for this instance.
     */
    readonly serviceAccountId?: pulumi.Input<string>;
    /**
     * The availability zone where the virtual machine will be created. If it is not provided,
     * the default provider folder is used.
     */
    readonly zone?: pulumi.Input<string>;
}
